providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm install --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
